# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10395bf62c07859385d5d666d49345f5788cb2477ae15091429f30b67007637691f099f2c7ecf8b1e049aa0d78b945f72d70b8195f694509b17a5ca9c3878170

test:
  secret_key_base: a8a8980d7c8c5ca9d5d53013f7c43a2235cfcd41b99df2bb519afbe850bf04fac9581e8fdc1f0827a468a28fa97a7d05c397d10d976cd9c2cc98029e02653b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
